<script>
    try{
        //code that may throw an error
        let num=10
        var b=0
        let result=num/b
        if(b==0){
            throw new Error("hiii error")
        }
        document.write("result:",result)
    }
    catch(err)
    {  //handle the error
        document.write("an error occured    ",err.message)
    }
    finally
    { //this block always executes
        document.write("execution completed")
    }
</script>